### ISSUE TITLE
Installing outside of zen-mods website?

### ISSUE THREAD

**Issue by mitchellurgero** [Uiniel/zen-mods#15]
I see the zen mods listing for this repo hasn't gone past 1.0.0 but there have been many updates since

is there a way for me to install this beyond that?

**Comment by Uiniel** [comment]
Yeah I haven't updated it yet since it has to be approved manually, so I wanted to publish it once I fixed all the bugs.

To try the current dev version:
- disable the mod
- add the content of chrome.css to your userChrome.css
- add the preferences:
    - the non-string preferences to about:config
![image](https://github.com/user-attachments/assets/48a700c1-87a4-491b-9a3d-e5edd83b6c77)
    - the string preferences to your userChrome.css like this:
```css
:root {
  --theme-sidebar_expand_on_hover-expanded_width: 300px !important;
  --theme-sidebar_expand_on_hover-transition_speed: 120ms !important;
}
```

**Comment by quirxsama** [comment]
Where is userChrome css file? can you help?

**Comment by Uiniel** [comment]
Just wanted to let you know that the version on the mod website is updated.

**Comment by mitchellurgero** [comment]
> Just wanted to let you know that the version on the mod website is updated.

New update is great! Good work on this :)
