### ISSUE TITLE
Black top border when expanded

### ISSUE THREAD

**Issue by nanocryk** [Uiniel/zen-mods#5]
When expanded the sidebar have a small black border. Would be great if it looked more subtle like at the bottom of the sidebar.

![image](https://github.com/user-attachments/assets/84688ee9-3e4a-4d73-b452-d9b704e5f4cd)
![image](https://github.com/user-attachments/assets/be2fae84-5f85-458a-ae5f-405e979d2787)

**Comment by Uiniel** [comment]
Oh yeah I added that drop shadow because with the theme I was using their was this really noticeable border around the side panel and that was the easiest way to hide it with the expanding sidebar. I'll make the shadow into an option the next version.
![image](https://github.com/user-attachments/assets/29e15162-2370-4115-95b3-58485a47b68a)
